;;; $DOOMDIR/config.el -*- lexical-binding: t; -*-

(setq! user-full-name "Luis Dale Gascon"
       user-mail-address "luis.gcodes@gmail.com")

(setq! doom-font (font-spec :family "ZedMono Nerd Font" :size 14)
       doom-variable-pitch-font (font-spec :family "Alegreya" :size 13)
       doom-big-font (font-spec :family "ZedMono Nerd Font" :size 25)
       line-spacing 0.10)

(after! treemacs
  (setq! treemacs-position 'right))

(use-package! auto-dark
  :init
  (setq! auto-dark-themes '((doom-ayu-dark) (doom-homage-white)))
  )

(whitespace-mode -1)
(delete-selection-mode +1)
(global-subword-mode +1)
(repeat-mode 1)
(global-goto-address-mode +1)
(setq! ns-use-native-fullscreen t)
(setq! tab-width 4)
(setq! truncate-string-ellipsis "…")
(setq! display-line-numbers-type 'relative)
(setq! confirm-kill-emacs nil)
(setq! frame-title-format "Notepad for the top 1\%% male")
;; Draggable window divider by increasing width
(setq! window-divider-default-right-width 3)
(setq! window-divider-default-bottom-width 0)
(setq! initial-scratch-message nil)

;; Possible fix?
;; Auto-save errors out since it tries to save within this path:
;; <default-directory + doom-profile-cache-dir> which doesn't exists and shouldn't
(setq! auto-save-file-name-transforms
       `(("\\`/[^/]*:\\([^/]*/\\)*\\([^/]*\\)\\'"
          ,(concat (file-name-as-directory doom-profile-cache-dir) "autosave/tramp/\\2-") sha1)
         (".*" ,(concat (file-name-as-directory doom-profile-cache-dir) "autosave/\\1-") sha1)))

(map!
 :desc "Disable mouse scroll that modifies text size"
 "<C-wheel-up>" nil
 "<C-wheel-down>" nil)

(after! consult
  (map!
   :leader
   :desc "Kill ring history"
   "s c" #'consult-yank-from-kill-ring)
  )

(after! writeroom-mode
  ;; Hide modeline
  ;; Slightly upsize text
  ;; Center text
  (setq! writeroom-mode-line nil
         +zen-text-scale 0
         writeroom-width 0.8)
  ;; Toggle line numbers
  (add-hook! 'writeroom-mode-enable-hook #'(lambda () (display-line-numbers-mode -1)))
  (add-hook! 'writeroom-mode-disable-hook #'(lambda () (display-line-numbers-mode 1)))
  ;; Disable writeroom from applying mixed-pitch text
  (remove-hook 'writeroom-mode-hook #'+zen-enable-mixed-pitch-mode-h)
  )

(after! corfu
  (setq! corfu-auto nil)
  )

;; Disable word suggestion popups
(setq! text-mode-ispell-word-completion nil)

(after! eglot
  (when (executable-find "harper-ls")
    (add-to-list 'eglot-server-programs '(text-mode . ("harper-ls" "--stdio")))
    )
  )

(after! org
  (defun my/org-capture-select-project-target ()
    "Select a project headline and move point to the desired sub-heading. Generated by Gemini 3 (Fast)"
    (let* ((file +org-capture-projects-file)
           ;; Projects are level 1 trees
           (projects (org-map-entries #'org-get-heading "LEVEL=1" (list file)))
           (selected (completing-read "Select Project: " projects nil t))
           (subheading (plist-get org-capture-plist :subheading)))
      (set-buffer (find-file-noselect file))
      (goto-char (point-min))
      ;; Find the project, then the specific subheading
      (re-search-forward (format org-complex-heading-regexp-format (regexp-quote selected)))
      (re-search-forward (format org-complex-heading-regexp-format (regexp-quote subheading)))))

  (setq! org-image-max-width 0.5)
  (setq! org-directory (expand-file-name "~/Documents/org/"))
  (setq! org-id-link-to-org-use-id 'create-if-interactive-and-no-custom-id)
  (setq! org-latex-compiler "lualatex")
  (setq! org-preview-latex-default-process 'dvisvgm)
  (when (modulep! :lang org +dragndrop)
    (setq! org-download-image-dir (expand-file-name "attachments" org-directory))
    )
  (map!
   :map org-mode-map
   :desc "Insert org heading" "C-s-<return>" #'org-insert-heading)
  (setq! org-refile-allow-creating-parent-nodes 'confirm)

  (setq! +org-capture-journal-file (expand-file-name "journal.org" org-directory)
         +org-capture-projects-file (expand-file-name "projects.org" org-directory)
         )
  (setq! org-capture-templates
         '(
           ("i" "Fleeting" entry
            (file+headline +org-capture-notes-file "Inbox")
            "* %^{Title}\n:PROPERTIES:\n:CREATED: %U\n:END:\n %i\n%?"
            :prepend t)

           ("n" "Notes" entry
            (file+headline +org-capture-notes-file "Notes")
            "* %^{Title}\n:PROPERTIES:\n:CREATED: %U\n:END:\n %i\n%?"
            :prepend t)

           ("m" "Meeting" entry (file+olp+datetree +org-capture-journal-file)
	    "* %T MEETING with %? %i:MEETING:\n%?" :clock-in t :clock-resume t)

           ("j" "Journal")
           ("jn" "Journal" entry
            (file+olp+datetree +org-capture-journal-file)
            "* %U %?\n %i" :prepend t)

           ("jd" "Journal on date" entry
            (file+datetree+prompt +org-capture-journal-file)
            "* %U %?\n %i"
            :prepend t)

           ("p" "Projects")
           ("pN" "New project" entry 
            (file +org-capture-projects-file)
            "* %^{Project Name}\n** Tasks\n** Notes")
           ("pt" "Project todo" entry
            (function my/org-capture-select-project-target)
            "* TODO %? %i"
            :subheading "Tasks"
            :prepend nil)

           ("pn" "Project notes" entry
            (function my/org-capture-select-project-target)
            "* %? %i"
            :subheading "Notes"
            :prepend t)
           )
         )

  (setq! org-agenda-files (directory-files org-directory t "\\.org$"))
  )

(after! dired
  (setq! dired-kill-when-opening-new-dired-buffer t))

(after! flycheck
  (flycheck-popup-tip-mode nil))

(after! which-key
  (setq! which-key-idle-delay 0.8))

(after! tex
  (setq! +latex-viewers '(skim pdf-tools)))

(after! markdown-mode
  (map!
   :map markdown-mode-map
   :desc "Next table cell" "<tab>" #'markdown-table-forward-cell
   :desc "Previous table cell" "S-<tab>" #'markdown-table-backward-cell)
  )

(after! vertico
  (map!
   :map vertico-map
   :desc "Scroll up" "C-v" #'scroll-up-command
   :desc "Scroll down" "M-v" #'scroll-down-command
   ))

(after! modus-themes
  (setq! modus-themes-fringes nil))

(when (featurep :system 'macos)
  (setq! ns-use-proxy-icon 'nil)
  (setq! mac-right-option-modifier 'meta))

(when (modulep! :editor word-wrap)
  (+global-word-wrap-mode 1))

(after! lsp-ui
  (setq! lsp-ui-doc-enable nil)
  (setq! lsp-ui-doc-delay 0.2)
  (setq! lsp-ui-doc-show-with-cursor nil)
  (setq! lsp-ui-doc-position 'top)
  (setq! lsp-ui-doc-max-width 120)
  (setq! lsp-ui-sideline-show-diagnostics nil)
  (setq! lsp-ui-imenu-window-fix-width t)
  (setq! lsp-ui-imenu-window-width 20)
  (setq! lsp-ui-sideline-show-diagnostics nil)
  )

(after! web-mode
  (setq! web-mode-code-indent-offset 4)
  (setq! web-mode-markup-indent-offset 2)
  (add-hook 'web-mode-hook #'web-mode-toggle-current-element-highlight)
  )

(after! markdown-mode
  (setq! markdown-unordered-list-item-prefix "  - ")
  )

(after! gptel
  (setq gptel-model 'gpt-4.1
        gptel-backend (gptel-make-gh-copilot "Copilot"))
  )


(setq! mode-line-format '("%e" mode-line-front-space
                          (:propertize
                           ("" mode-line-mule-info
                            mode-line-client
                            mode-line-modified
                            mode-line-remote
                            mode-line-window-dedicated)
                           display (min-width (6.0)))
                          mode-line-frame-identification
                          mode-line-buffer-identification "   "
                          mode-line-position
                          (project-mode-line project-mode-line-format)
                          (vc-mode vc-mode) "  "
                          ;; mode-line-modes
                          mode-name
                          ;; mode-line-misc-info
                          mode-line-end-spaces
                          )
       )

(map! "C-z" nil :desc "Disable suspend frame keymap")
