;;; $DOOMDIR/config.el -*- lexical-binding: t; -*-

(setq user-full-name "Luis Dale Gascon"
      user-mail-address "luis.gcodes@gmail.com")

(setq doom-font (font-spec :family "DejaVuSansM Nerd Font Mono" :size 14)
      doom-variable-pitch-font (font-spec :family "Helvetica Neue" :size 16)
      doom-big-font (font-spec :family "ZedMono Nerd Font" :size 25)
      line-spacing 0.10)

(after! treemacs
  (setq treemacs-position 'right))

(setq +format-on-save-disabled-modes
      '(sql-mode org-msg-edit-mode git-commit-mode))

(use-package! auto-dark
  :init
  (setopt auto-dark-themes '((doom-dracula) (modus-operandi)))
  )

(whitespace-mode -1)
;; Replace selected region with yanked
(delete-selection-mode +1)
(global-subword-mode +1)
(repeat-mode 1)
(global-goto-address-mode +1)
(setq tab-width 4)
(setq truncate-string-ellipsis "…")
(setq display-line-numbers-type 'relative)
(setq confirm-kill-emacs nil)
(setq frame-title-format "Scuffed Cursor")
(setq initial-scratch-message nil)

(map!
 :desc "Disable mouse scroll that modifies text size"
 "<C-wheel-up>" nil
 "<C-wheel-down>" nil)

(after! consult
  (map!
   :leader
   :desc "Kill ring history"
   "s c" #'consult-yank-from-kill-ring)
  )

(after! writeroom-mode
  ;; Hide modeline
  ;; Slightly upsize text
  ;; Center text
  (setq 
   +zen-text-scale 0
   writeroom-width 0.8)
  ;; Toggle line numbers
  (add-hook! 'writeroom-mode-enable-hook #'(lambda () (display-line-numbers-mode -1)))
  (add-hook! 'writeroom-mode-disable-hook #'(lambda () (display-line-numbers-mode 1)))
  ;; Disable writeroom from applying mixed-pitch text
  (remove-hook 'writeroom-mode-hook #'+zen-enable-mixed-pitch-mode-h)
  )

;; Disable word suggestion popups
(setq text-mode-ispell-word-completion nil)

(after! eglot
  ;; Keep the echo area from expanding up
  (setq eldoc-echo-area-use-multiline-p nil)
  (setq eldoc-echo-area-prefer-doc-buffer t)
  )

(after! org-roam
  ;; org-roam is strictly for learning
  (setq org-roam-directory (expand-file-name "~/Documents/org/roam"))
  (setq org-roam-capture-templates
        '(("p" "permanent" plain
           "* ${title}\n%?"
           :target
           (file+head
            "${slug}.org"
            "#+title: ${title}\n#+filetags: permanent\n#+DATE: %u\n")
           :unnarrowed t)
          ("l" "literature" plain
           "* ${title}\n%?"
           :target
           (file+head
            "${slug}.org"
            "#+title: ${title} \n#+filetags: literature\n#+DATE: %u\n")
           :unnarrowed t)
          ("c" "citar-literature" plain
           "%?"
           :target
           (file+head
            "${citar-citekey}.org"
            "#+title: ${citar-citekey} (${citar-date}) \n#+filetags: literature\n#+DATE: %u")
           :unnarrowed t)
          )
        )

  (setq org-roam-dailies-capture-templates
        '(("d" "default"
           entry
           "* %<%H:%M>\n** %?"
           :if-new (file+head "%<%Y-%m-%d>.org"
                              "#+title: %<%Y-%m-%d>\n")
           :empty-lines 1)
          )
        ))

(after! org
  (setq org-todo-keywords
	'(
          ;; Project todos
          (sequence "TODO" "WIP" "DONE")
          ;; Note-taking todos
          (sequence "INBOX(i)"
	            "PROCESSING(p)"
	            "WAIT(w)"
	            "TO-READ(r)"
	            "|"
	            "DONE(d)"
	            )))
  (defun my/org-capture-select-project-target ()
    "Select a project headline and move point to the desired sub-heading. Generated by Gemini 3 (Fast)"
    (let* ((file +org-capture-projects-file)
           ;; Projects are level 1 trees
           (projects (org-map-entries #'org-get-heading "LEVEL=1" (list file)))
           (selected (completing-read "Select Project: " projects nil t))
           (subheading (plist-get org-capture-plist :subheading)))
      (set-buffer (find-file-noselect file))
      (goto-char (point-min))
      ;; Find the project, then the specific subheading
      (re-search-forward (format org-complex-heading-regexp-format (regexp-quote selected)))
      (re-search-forward (format org-complex-heading-regexp-format (regexp-quote subheading)))))

  (setq org-image-max-width 0.5)
  (setq org-directory (expand-file-name "~/Documents/org/"))
  (setq org-id-link-to-org-use-id 'create-if-interactive-and-no-custom-id)
  (setq org-latex-compiler "lualatex")
  (when (modulep! :lang org +dragndrop)
    (setq org-download-image-dir (expand-file-name "attachments" org-directory))
    )
  (map!
   :map org-mode-map
   :desc "Insert org heading" "C-s-<return>" #'org-insert-heading)
  (setq org-refile-allow-creating-parent-nodes 'confirm)

  (setq +org-capture-journal-file (expand-file-name "journal.org" org-directory)
        +org-capture-projects-file (expand-file-name "projects.org" org-directory)
        )

  (setq org-capture-templates
        ;; Vanilla org is used for project, journals and meetings
        '(
          ("j" "Journal")
          ("jn" "Journal" entry
           (file+olp+datetree +org-capture-journal-file)
           "* %<%I:%M %p>\n%?" :prepend t :tree-type (year month day)
           )

          ("jd" "Journal on date" entry
           (file+olp+datetree +org-capture-journal-file)
           "* %?"
           :prepend t :time-prompt t :tree-type (year month day)
           )

          ("jw" "Work log" entry
           (file+olp+datetree "work-log.org")
           "* %?" :clock-in t :clock-keep t :tree-type (year month week day)
           )

          ("p" "Projects")
          ("pN" "New project" entry
           (file +org-capture-projects-file)
           "* %^{Project Name}\n** Tasks\n** Notes")
          ("pt" "Project todo" entry
           (function my/org-capture-select-project-target)
           "* TODO %? %i"
           :subheading "Tasks"
           :prepend nil)

          ("pn" "Project notes" entry
           (function my/org-capture-select-project-target)
           "* %? %i"
           :subheading "Notes"
           :prepend t)
          )
        )

  (setq org-agenda-files
        (append
         (when (file-directory-p org-directory)
           (directory-files org-directory t "\\.org$"))
         ))
  )

(after! dired
  (setq dired-kill-when-opening-new-dired-buffer t))

(after! flycheck
  (flycheck-popup-tip-mode -1))

(after! which-key
  (setq which-key-idle-delay 0.8))


(after! markdown-mode
  (map!
   :map markdown-mode-map
   :desc "Next table cell" "<tab>" #'markdown-table-forward-cell
   :desc "Previous table cell" "S-<tab>" #'markdown-table-backward-cell)
  )

(after! vertico
  (setq vertico-count 10)
  (map!
   :map vertico-map
   :desc "Scroll up" "C-v" #'scroll-up-command
   :desc "Scroll down" "M-v" #'scroll-down-command
   ))

(after! modus-themes
  (setq modus-themes-fringes nil))

(when (featurep :system 'macos)
  (setq ns-use-proxy-icon 'nil)
  ;; Occupy a space if MacOS fullscreen
  (setq ns-use-native-fullscreen t)
  (setq mac-right-option-modifier 'meta))

(when (modulep! :editor word-wrap)
  (+global-word-wrap-mode 1))

(after! lsp-ui
  (setq lsp-ui-doc-enable nil)
  (setq lsp-ui-doc-delay 0.2)
  (setq lsp-ui-doc-show-with-cursor nil)
  (setq lsp-ui-doc-position 'top)
  (setq lsp-ui-doc-max-width 120)
  (setq lsp-ui-sideline-show-diagnostics nil)
  (setq lsp-ui-imenu-window-fix-width t)
  (setq lsp-ui-imenu-window-width 20)
  (setq lsp-ui-sideline-show-diagnostics nil)
  )

(after! markdown-mode
  (setq markdown-unordered-list-item-prefix "  - ")
  )

(after! gptel
  ;; Dock gptel on the left
  (set-popup-rule!
    (lambda (bname _action)
      (and (null gptel-display-buffer-action)
           (buffer-local-value 'gptel-mode (get-buffer bname))))
    :select t
    :size 0.3
    :quit nil
    :side 'left
    :ttl nil)
  )

(defun nf/parse-headline (x)
  (plist-get (cadr x) :raw-value))

(defun nf/get-headlines ()
  (org-element-map (org-element-parse-buffer) 'headline #'nf/parse-headline))

(defun user/link-to-headline ()
  "Insert an internal link to a headline."
  (interactive)
  (let* ((headlines (nf/get-headlines))
	 (choice (completing-read "Headings: " headlines nil t))
	 (desc (read-string "Description: " choice)))
    (org-insert-link buffer-file-name (concat "*" choice) desc)))

(map! "C-z" nil :desc "Disable suspend frame keymap")

(after! citar
  (setq citar-org-roam-capture-template-key "c")
  (setq org-cite-global-bibliography '("~/bib/ReferenceLibrary.bib"))
  (setq citar-bibliography org-cite-global-bibliography)
  )
