{ ... }:
{
  flake.homeModules."personal-latexmkrc" =
    { ... }:
    {
      home.file.".latexmkrc".text = ''

        # Generated by Claude
        # Output directory
        $out_dir = 'out';
        $aux_dir = "out";

        # Create output directory if it doesn't exist
        system("mkdir -p $out_dir");

        # Use PDF mode with LuaLaTeX
        $pdf_mode = 4;

        # Use lualatex and put auxiliary files in out directory
        $lualatex = 'lualatex -interaction=nonstopmode -synctex=1 -file-line-error -output-directory=' . $out_dir;

        # Keep auxiliary files in the output directory
        $emulate_aux = 1;

        # Files to clean
        $clean_ext = 'aux bbl blg log fdb_latexmk fls out toc synctex.gz run.xml';

        # Clean up the auxiliary files in the output directory
        $clean_up_dir = 1;

        # Only move pdf files to output directory, leave auxiliary files in out dir
        @generated_exts = ('aux', 'bbl', 'bcf', 'fls', 'idx', 'ind', 'lof', 'lot', 'out', 'run.xml', 'synctex.gz', 'toc');
        foreach $ext (@generated_exts) {
            $aux_source_ext_pairs{$ext} = "$out_dir/%R.$ext";
        }

      '';
    };
}
