{
  pkgs,
  config,
  ...
}:

{
  imports = [
    ./shared.nix
    ../modules/ghostty
  ];

  home.packages = with pkgs; [
    # Fonts
    nerd-fonts.fira-code
    nerd-fonts.jetbrains-mono
    nerd-fonts.roboto-mono
    nerd-fonts.zed-mono
    julia-mono
  ];

  xdg.configFile.".latexmkrc".text = ''

    # Generated by Claude
    # Output directory
    $out_dir = 'out';

    # Create output directory if it doesn't exist
    system("mkdir -p $out_dir");

    # Use PDF mode with LuaLaTeX
    $pdf_mode = 4;  # Mode 4 is for LuaLaTeX

    # Use lualatex and put auxiliary files in out directory
    $lualatex = 'lualatex -interaction=nonstopmode -synctex=1 -file-line-error -output-directory=' . $out_dir;

    # Run cleanup after successful compilation
    $success_cmd = 'latexmk -c %S';

    # Keep auxiliary files in the output directory
    $emulate_aux = 1;

    # Clean up auxiliary files after successful build
    $cleanup_mode = 2;  # Clean up more aggressively

    # Files to clean
    $clean_ext = 'aux bbl blg log fdb_latexmk fls out toc synctex.gz run.xml';

    # Clean up the auxiliary files in the output directory
    $clean_up_dir = 1;

    # Only move pdf files to output directory, leave auxiliary files in out dir
    @generated_exts = ('aux', 'bbl', 'bcf', 'fls', 'idx', 'ind', 'lof', 'lot', 'out', 'run.xml', 'synctex.gz', 'toc');
    foreach $ext (@generated_exts) {
        $aux_source_ext_pairs{$ext} = "$out_dir/%R.$ext";
    }

  '';

  # PATH
  home.sessionPath = [
    "/opt/homebrew/bin"
    "${config.home.homeDirectory}/.local/bin"
    # Haskell
    "${config.home.homeDirectory}/.ghcup/bin"
    # Doom Emacs binaries
    "${config.home.homeDirectory}/.config/emacs/bin"
  ];

  programs.fish = {
    interactiveShellInit =
      # Add brew completions to Fish
      ''
        if test -d (brew --prefix)"/share/fish/completions"
          set -p fish_complete_path (brew --prefix)/share/fish/completions
        end

        if test -d (brew --prefix)"/share/fish/vendor_completions.d"
          set -p fish_complete_path (brew --prefix)/share/fish/vendor_completions.d
        end
      '';

    plugins = [
      # Allow Fish as a default macOS shell in order to pick up ~/.nix-profile/bin
      {
        name = "nix-env";
        src = pkgs.fetchFromGitHub {
          owner = "lilyball";
          repo = "nix-env.fish";
          rev = "7b65bd228429e852c8fdfa07601159130a818cfa";
          sha256 = "069ybzdj29s320wzdyxqjhmpm9ir5815yx6n522adav0z2nz8vs4";
        };
      }
    ];
  };

  programs.git = {
    settings = {
      credential.helper = "osxkeychain";
      ssh = {
        AddKeysToAgent = "yes";
        UseKeychain = "yes";
      };
    };
  };
}
