{
  config,
  lib,
  pkgs,
  ...
}:

{
  imports = [
    ./shared.nix
    ./macos.nix
  ];

  home.packages = with pkgs; [
    # GUI apps
    obsidian
    skimpdf
    iina
    utm
  ];

  home.sessionPath = [
    # Haskell
    "${config.home.homeDirectory}/.ghcup/bin"
  ];

  home.file.".latexmkrc".text = ''

    # Generated by Claude
    # Output directory
    $out_dir = 'out';

    # Create output directory if it doesn't exist
    system("mkdir -p $out_dir");

    # Use PDF mode with LuaLaTeX
    $pdf_mode = 4;  # Mode 4 is for LuaLaTeX

    # Use lualatex and put auxiliary files in out directory
    $lualatex = 'lualatex -interaction=nonstopmode -synctex=1 -file-line-error -output-directory=' . $out_dir;

    # Run cleanup after successful compilation
    $success_cmd = 'latexmk -c %S';

    # Keep auxiliary files in the output directory
    $emulate_aux = 1;

    # Clean up auxiliary files after successful build
    $cleanup_mode = 2;  # Clean up more aggressively

    # Files to clean
    $clean_ext = 'aux bbl blg log fdb_latexmk fls out toc synctex.gz run.xml';

    # Clean up the auxiliary files in the output directory
    $clean_up_dir = 1;

    # Only move pdf files to output directory, leave auxiliary files in out dir
    @generated_exts = ('aux', 'bbl', 'bcf', 'fls', 'idx', 'ind', 'lof', 'lot', 'out', 'run.xml', 'synctex.gz', 'toc');
    foreach $ext (@generated_exts) {
        $aux_source_ext_pairs{$ext} = "$out_dir/%R.$ext";
    }

  '';

  modules = {
    ghostty.enable = true;
  };
}
